#!/bin/bash

die()
{
    echo 'ERROR:' $@
    exit 1
}

[ "$#" -eq 2 ] || die "please launch using $0 <avd_name> <num_of_instances>"
echo $2 | grep -E -q '^[0-9]+$' || die "Numeric argument required, $2 provided"

[ -z "$ANDROID_SDK" ] && die 'No $ANDROID_SDK specified'

adt_tools=$ANDROID_SDK/tools/
emulator_path=$adt_tools/emulator

[ -z "emulator_path" ] && die "Could not locate AVD emulator"

#Check the AVD list
avd_list=`$adt_tools/android list avd | grep Name | grep $1 | awk '{print $2}'`

for avd in $avd_list; do
    if [ $avd == $1 ]; then
        avd_found='y'
    fi
done

if [ -z "$avd_found" ]; then
    echo "No AVD device found with '$1' name, printing available AVD devices..."
    $adt_tools/android list avd
    exit 1
fi

for i in `seq 1 $2`; do
    echo "Launching emulator with shared-net-id $i"
    $emulator_path @$1 -shared-net-id $i > /dev/null 2>&1 &
done
